set_property PACKAGE_PIN P1       [ get_ports {GPIO_LED[0]} ]
set_property PACKAGE_PIN N2       [ get_ports {GPIO_LED[1]} ]
# set_property PACKAGE_PIN M2       [ get_ports {GPIO_LED[2]} ]
# set_property PACKAGE_PIN L2       [ get_ports {GPIO_LED[3]} ]
# set_property PACKAGE_PIN J1       [ get_ports {GPIO_LED[4]} ]
# set_property PACKAGE_PIN H2       [ get_ports {GPIO_LED[5]} ]
# set_property PACKAGE_PIN L4       [ get_ports {GPIO_LED[6]} ]
# set_property PACKAGE_PIN L3       [ get_ports {GPIO_LED[7]} ]
set_property IOSTANDARD  LVCMOS18 [ get_ports -regexp {GPIO_LED\[\d\]} ]
