name: Memory Testing

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  NVC:
    name: ${{ matrix.icon }}${{ matrix.name }} - NVC
    runs-on: ${{ matrix.image }}
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {icon: "🐧",   name: "Ubuntu",  image: "ubuntu-24.04", shell: "bash",     can-fail: true}
##        - {icon: "🪟",   name: "Windows", image: "windows-2022", shell: "powershell"}      # Scripting is Bash-based
##        - {icon: "🪟🟨", name: "Windows", image: "windows-2022", shell: "msys2 {0}"}       # Installation in Windows via MSI, but called from UCRT64.

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: ${{ matrix.icon }} Setup MSYS2 for UCRT64
        uses: msys2/setup-msys2@v2
        if: matrix.name == 'Windows' && startsWith(matrix.shell, 'msys2')
        with:
          msystem: ucrt64
          update: true

      - name: 🔧 Install NVC
        uses: nickg/setup-nvc-ci@v1
        with:
          version: latest

      - name: Prepare
        run: |
          mv src/PoC/my_project.vhdl.template src/PoC/my_project.vhdl

      - name: 🚧 Run tests on Ubuntu
        if: matrix.name == 'Ubuntu'
        run: |
          mkdir -p temp
          cd temp

          sed -i 's|StartUp|StartNVC|' ../regression.tcl
          nvc --do ../regression.tcl

      - name: 🚧 Run tests on Windows + MSYS2/UCRT64
        if: matrix.name == 'Windows' && startsWith(matrix.shell, 'msys2')
        run: |
          export PATH="/c/Program Files/NVC/bin:$PATH"

          mkdir -p temp
          cd temp

          ../scripts/NVC.sh

      - name: 🚧 Inspect Ant+JUnit Unittest Summary XML
#        if: matrix.name == 'Ubuntu'
        run: |
          cat temp/*.xml

      - name: '📤 Upload artifact: logs'
        uses: actions/upload-artifact@v6
        with:
          name: junit-${{ matrix.name }}-nvc
          include-hidden-files: true
          path: |
            temp/*.xml
          if-no-files-found: error
          retention-days: 1

  GHDL:
    name: ${{ matrix.icon }}${{ matrix.name }} - GHDL [${{ matrix.backend }}]
    runs-on: ${{ matrix.image }}
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {icon: "🐧",   name: "Ubuntu",  image: "ubuntu-24.04", shell: "bash",      can-fail: true,  backend: "llvm"}
          - {icon: "🐧",   name: "Ubuntu",  image: "ubuntu-24.04", shell: "bash",      can-fail: false, backend: "mcode"}
##        - {icon: "🪟",   name: "Windows", image: "windows-2022", shell: "powershell"}      # Scripting is Bash-based
##        - {icon: "🪟🟨", name: "Windows", image: "windows-2022", shell: "msys2 {0}"}       # Installation in Windows via MSI, but called from UCRT64.

    defaults:
      run:
        shell: ${{ matrix.shell }}

    steps:
      - name: ⏬ Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: ${{ matrix.icon }} Setup MSYS2 for UCRT64
        uses: msys2/setup-msys2@v2
        if: matrix.name == 'Windows' && startsWith(matrix.shell, 'msys2')
        with:
          msystem: ucrt64
          update: true

      - name: 🔧 Install tcllib
        run: sudo apt-get install -y --no-install-recommends tcllib

      - name: 🔧 Install GHDL
        uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: ${{ matrix.backend }}

      - name: Prepare
        run: |
          mv src/PoC/my_project.vhdl.template src/PoC/my_project.vhdl

      - name: 🚧 Run tests on Ubuntu
        if: matrix.name == 'Ubuntu'
        run: |
          mkdir -p temp
          cd temp

          tclsh ../regression.tcl

      - name: 🚧 Run tests on Windows + MSYS2/UCRT64
        if: matrix.name == 'Windows' && startsWith(matrix.shell, 'msys2')
        run: |
          export PATH="/c/Program Files/NVC/bin:$PATH"

          mkdir -p temp
          cd temp

          ../scripts/NVC.sh

      - name: 🚧 Inspect Ant+JUnit Unittest Summary XML
#        if: matrix.name == 'Ubuntu'
        run: |
          cat temp/tb_RunAllTests/*.xml

      - name: '📤 Upload artifact: logs'
        uses: actions/upload-artifact@v6
        with:
          name: junit-${{ matrix.name }}-ghdl-${{ matrix.backend }}
          include-hidden-files: true
          path: |
            temp/tb_RunAllTests/*.xml
          if-no-files-found: error
          retention-days: 1

  PublishTestResults:
    uses: pyTooling/Actions/.github/workflows/PublishTestResults.yml@r7
    needs:
      - NVC
      - GHDL
    with:
      unittest_artifacts_pattern: "junit-*"
      testsuite-summary-name:     "Interfaces"
      dorny:                      true
#      codecov:                    true
    secrets: inherit
